comment: false

ignore:
  - "R/ArchaeoPhases-deprecated.R"
  - "R/ArchaeoPhases-defunct.R"
  - "R/zzz.R"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
