#####################################################
#             Importing a CSV file                  #
#####################################################
#' Importing a CSV file
#'
#' Import a CSV file containing the output of the MCMC algorithm
#'
#' Use of the \code{read.csv()} function with default values for CSV files produced by
#' \href{https://chronomodel.com}{ChronoModel} software. For MCMC in a date format
#' different from BC/AD, use the
#' parameter \code{referenceYear} to convert the MCMC to BC/AD, otherwise the
#' remaining functions of \pkg{ArchaeoPhases} will not work. MCMC files generated by
#' \href{https://bcal.shef.ac.uk/top.html}{BCal} may contain an empty last row. This row
#' should be withdrawn using the \code{rowToWithdraw} parameter.
#' Otherwise, the functions of \pkg{ArchaeoPhases} will not work properly.
#'
#' @param file Name of the CSV file containing the output of the MCMC algorithm.
#' @param dec Character used in the file for decimal points for the use of \code{read.csv()}.
#' @param sep Field separator character for the use of \code{read.csv()}.
#' @param comment.char Character vector of length one containing a single
#' character or an empty string for the use of \code{read.csv()}.
#' @param header Logical value indicating whether the file contains the names
#' of the variables as its first line.
#' @param iterationColumn Column number corresponding to the iteration values,
#' default = \code{NULL}.
#' @param referenceYear Year of reference for MCMC in date format other than
#' BC/AD, default = \code{NULL}.
#' @param rowToWithdraw Number of the row to be withdrawn or "last" for the
#' last row of the data frame, default = \code{NULL}.
#' @param bin.width Bin width specified in a BCal project (note that \code{bin.width}
#' does not have to be set if the BCal default bin width of 1 is used).
#'
#' @return A data frame containing a representation of the data in the file.
#'
#' @author Anne Philippe, \email{Anne.Philippe@@univ-nantes.fr},
#' @author Thomas S. Dye, \email{tsd@@tsdye.online}, and
#' @author  Marie-Anne Vibet, \email{Marie-Anne.Vibet@@univ-nantes.fr}
#'
#' @examples
#'
#'   data(Events)
#'   write.csv(Events, "data.csv", row.names=FALSE)
#'   data = ImportCSV("data.csv", dec = '.', sep=',', comment.char='#', header = TRUE,
#'                    iterationColumn = 1)
#'
#'   # Import of MCMC generated by BCal and extracted in cal BP (the year of reference is 1950)
#'   # data(Fishpond)
#'   # write.csv(Fishpond, "fishpond_MCMC.csv", row.names=FALSE)
#'   # Fishpond = ImportCSV("fishpond_MCMC.csv", dec = '.', sep=',', header = TRUE,
#'   #                       iterationColumn = 1, referenceYear = 1950, rowToWithdraw = "last")
#'
#' @seealso \code{\link{ImportCSV.BCal}}
#'
#' @importFrom utils read.csv
#'
#' @export
#'
ImportCSV <- function(file, dec='.', sep=',', comment.char = '#',
                      header = TRUE, iterationColumn = NULL,
                      referenceYear = NULL, rowToWithdraw = NULL,
                      bin.width = NULL)
{
  # importing the CSV file
  data = read.csv(file, dec = dec, sep=sep, comment.char = comment.char,
                  header = header)

  # Withdrawing the iterations column
  if (!is.null(iterationColumn)){
    data = data[,-iterationColumn]
  }

  # Withdrawing a row
  if (!is.null(rowToWithdraw)){
    if (is.numeric(rowToWithdraw)) {
      data = data[-rowToWithdraw, ]
    }else{
      if (rowToWithdraw == "last") {
        data = data[-nrow(data), ]
      }
    }
  }

  # BCal bin width
  if (!is.null(bin.width)) {
    L = length(data)
    unbin <- function(value, width) {
      value * width
    }
    for (i in 1:L) {
      if (is.numeric(data[, i]) == TRUE) {
        data[, i] = sapply(data[, i], unbin, bin.width)
      }

    }
  }

  # Conversion of the MCMC samples in date format cal BP or other to BC/AD
  if (!is.null(referenceYear)){
    data2 = data
    L = length(data)
    conv <- function(value, T0){
      T0 - value
    }
    for (i in 1:L){
      if( is.numeric(data[,i]) == TRUE){
        data2[,i] = sapply(data[,i], conv, referenceYear)
      }
    }

    data = data2
  }

  return(data)





}
